name: Continuous Deployment - Lambda

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      version:
        required: true
        type: string
      role-to-assume:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Provision & Deploy Backend
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout Application Code
        uses: actions/checkout@v4
        with:
          path: app-repo

      - name: Checkout Infrastructure Code
        uses: actions/checkout@v4
        with:
          repository: AGES-RFID/cicd
          path: cicd-repo

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Publish & Zip Backend
        working-directory: app-repo
        run: |
          dotnet publish Backend.API/Backend.API.csproj -c Release -o ./publish -r linux-x64 --self-contained true
          cd publish
          mv Backend.API bootstrap
          zip -r ../deploy-${{ inputs.version }}.zip .

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role-to-assume }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Apply (Backend & Database)
        working-directory: cicd-repo/terraform
        run: |
          terraform init
          terraform apply \
            -target=aws_s3_bucket.artifacts \
            -target=aws_db_instance.postgres \
            -target=aws_lambda_function.backend \
            -target=aws_apigatewayv2_api.http_api \
            -target=aws_apigatewayv2_stage.default \
            -target=aws_apigatewayv2_integration.lambda_integration \
            -target=aws_apigatewayv2_route.default_route \
            -target=aws_lambda_permission.api_gw \
            -var-file=${{ inputs.environment }}.tfvars -auto-approve

          TF_LAMBDA=$(terraform output -raw backend_lambda_name)
          TF_BUCKET=$(terraform output -raw artifacts_bucket_name)

          echo "TARGET_LAMBDA=$TF_LAMBDA" >> $GITHUB_ENV
          echo "ARTIFACTS_BUCKET=$TF_BUCKET" >> $GITHUB_ENV

      - name: Update Lambda Function Code via S3
        working-directory: app-repo
        run: |
          # Variável auxiliar para manter o script limpo
          ARTIFACT_NAME="deploy-${{ inputs.version }}.zip"

          echo "[INFO] Enviando artefato para o S3..."
          aws s3 cp $ARTIFACT_NAME s3://$ARTIFACTS_BUCKET/releases/$ARTIFACT_NAME

          echo "[INFO] Instruindo a Lambda a utilizar o novo artefato..."
          aws lambda update-function-code \
            --function-name $TARGET_LAMBDA \
            --s3-bucket $ARTIFACTS_BUCKET \
            --s3-key releases/$ARTIFACT_NAME
            
          echo "[SUCCESS] Deploy Backend concluído."
