name: Continuous Deployment - S3

on:
  workflow_call:
    inputs:
      environment:
        description: "Ambiente de destino (staging, production)"
        required: true
        type: string
      version:
        description: "Versão a ser implantada (SHA ou Tag)"
        required: true
        type: string
      role-to-assume:
        description: "ARN da Role OIDC na AWS"
        required: true
        type: string
      s3-bucket-name:
        description: "Nome do Bucket S3 de destino"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to AWS S3
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Log Deployment Info
        run: |
          echo "[INFO] Iniciando implantação para o ambiente: ${{ inputs.environment }}"
          echo "[INFO] Versão do artefato: ${{ inputs.version }}"
          echo "[INFO] Bucket S3 alvo: ${{ inputs.s3-bucket-name }}"

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: dist/

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role-to-assume }}
          aws-region: us-east-2

      - name: Push Dist Folder to S3
        run: |
          aws s3 sync dist/ s3://${{ inputs.s3-bucket-name }}/frontend/ \
            --delete \
            --exclude "*.map"
          echo "[SUCCESS] Sincronização com o S3 concluída com sucesso."
